---

all:
  children:
    k8s:
      children:
        k8smasters:
          hosts:
            k8smaster1.example.com:
            k8smaster2.example.com:
            k8smaster3.example.com:
        k8sworkers:
          hosts:
            k8sworker1.example.com:
            k8sworker2.example.com:
