---

all:
  children:
    k8s:
      children:
        k8smasters:
          hosts:
            master1.example.com:
            master2.example.com:
            master3.example.com:
        k8sworkers:
          hosts:
            worker1.example.com:
            worker2.example.com:
            worker3.example.com:

