---

all:
  children:
    k8s:
      children:
        k8smasters:
          hosts:
            rpiblade2.example.com:
            rpiblade3.example.com:
            rpiblade4.example.com:
        k8sworkers:
          hosts:
            rpiblade5.example.com:
            rpiblade6.example.com:
            rpiblade7.example.com:

