---

keepalived_vip_for:
  - kubernetes

keepalived_vrrp_instances:
  - name:       k8s_api
    master_node: master1.example.com
    backup_nodes:
      - master2.example.com
      - master3.example.com
    virt_ip:
      - 192.168.1.10              # VIP for the k8s API — update to your network
